version: '3'

services:
  app:
    build:
      context: .docker
      dockerfile: Dockerfile
      target: prod
    image: symfony_doc_bot
    container_name: symfony_doc_bot
    dns:
      - 8.8.8.8
    volumes:
      - .:/var/www/html:rw
    command: ["php", "-S", "127.0.0.1:8000", "-t", "public"]
    ports:
      - 80:8000