---
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $openAiApiKey: '%env(OPENAI_API_KEY)%'

    App\Service\ChatManager:
        public: true
