name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Preprare environment
        run: cp .env .env.local && cp .env.docker .env.docker.local

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make test-coverage-ci

      - uses: actions/upload-artifact@v2
        with:
          name: phpunit-coverage
          path: phpunit.coverage.xml
  
      - uses: actions/upload-artifact@v2
        with:
          name: phpunit-report
          path: phpunit.report.xml

      - uses: actions/download-artifact@v2
        with:
          name: phpunit-coverage

      - uses: actions/download-artifact@v2
        with:
          name: phpunit-report
          
      - name: Fix code coverage paths
        run: sed -i 's@'/var/www/'@/github/workspace/@g' phpunit.coverage.xml phpunit.report.xml

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
