name: Lint

on: [push]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Preprare environment
              run: cp .env .env.local && cp .env.docker .env.docker.local && sed -i 's/ENV=dev/ENV=test/g' .env.docker.local
      
            - name: Install dependencies
              run: make install-test

            - name: Lint code
              run: make sf-lint-ci

            - name: Phpstan
              run: make phpstan-ci

            - name: Phpcsfixer
              run: make php-cs-fixer-dry-run-ci

            - name: Run tests
              run: make test-ci

            - name: Stop containers
              if: always()
              run: make docker-down-ci
